// Re-export barrel that preserves the original `@/lib/api` (no-extension)
// resolution path. The actual client, token helpers, ApiError, and all
// `xxxApi` modules live in `./api/index.ts`; this file re-exports them so that
// `import { agentsApi } from "@/lib/api"` keeps working and resolves to the
// real implementations instead of an empty stub.
//
// Historical: this file used to host the axios client only, which made Vite
// prefer it over the sibling `./api/index.ts` directory entry and broke
// every page importing `xxxApi` from `@/lib/api`.
export {
  client,
  getToken,
  setToken,
  clearToken,
  ApiError,
  type ApiEnvelope,
  authApi,
  usersApi,
  profilesApi,
  learningApi,
  coursesApi,
  resourcesApi,
  feedbackApi,
  agentsApi,
  promptsApi,
  invocationsApi,
  modelsApi,
  logsApi,
  statisticsApi,
  tutorApi,
  multimodalApi,
  platformSettingsApi,
  type TutorChatResponse,
  type Citation,
  type PracticeQuestion,
  type RecommendedResource,
  type ImageUnderstandResult,
  type GovernanceSettings,
  type GovernanceSettingsUpdate,
  type BudgetAlertSettings,
  type BudgetAlertSettingsUpdate,
  type UserInfo,
  type LoginResponse,
  type User,
  type Role,
  type Permission,
  type ProfileDetail,
  type Course,
  type KnowledgePoint,
  type LearningTask,
  type LearningPathNode,
  type LearningPathEdge,
  type LearningPathSummary,
  type LearningPathGraph,
  type LearningResource,
  type LearningFeedback,
  type AgentRequest,
  type WorkflowResult,
  type SaveResourceResponse,
  type PromptTemplate,
  type PromptVersion,
  type PromptTaskType,
  type CreateTemplateBody,
  type UpdateTemplateBody,
  type CreateVersionBody,
  type PromptRenderResult,
  type Invocation,
  type InvocationDetail,
  type ModelProvider,
  type AIModel,
  type TaskType,
  type ApiConfig,
  type OperationLog,
  type LoginLog,
  type ModelCallStats,
  type CostStats,
  type LearningOverview,
  type MasteryDist,
  type WeakKnowledgePoint,
  type ResourceTypeDist,
  type InvocationTrend,
  type ReviewRateByCourse,
  type CostDistribution,
} from './api/index'

export { client as default } from './api/index'
