// Re-export barrel that preserves the original `@/lib/api` (no-extension)
// resolution path. The actual client, token helpers, ApiError, and all
// `xxxApi` modules live in `./api/index.ts`; this file re-exports them so that
// `import { agentsApi } from "@/lib/api"` keeps working and resolves to the
// real implementations instead of an empty stub.
//
// Historical: this file used to host the axios client only, which made Vite
// prefer it over the sibling `./api/index.ts` directory entry and broke
// every page importing `xxxApi` from `@/lib/api`.
export {
  client,
  getToken,
  setToken,
  clearToken,
  ApiError,
  type ApiEnvelope,
  authApi,
  usersApi,
  profilesApi,
  learningApi,
  coursesApi,
  resourcesApi,
  feedbackApi,
  agentsApi,
  tasksApi,
  projectsApi,
  artifactsApi,
  promptsApi,
  reviewsApi,
  invocationsApi,
  modelsApi,
  logsApi,
  statisticsApi,
  tutorApi,
  multimodalApi,
  type TutorChatResponse,
  type Citation,
  type PracticeQuestion,
  type RecommendedResource,
  type ImageUnderstandResult,
  type UserInfo,
  type LoginResponse,
  type User,
  type Role,
  type Permission,
  type ProfileDetail,
  type Course,
  type KnowledgePoint,
  type LearningTask,
  type LearningPathNode,
  type LearningPathEdge,
  type LearningPathSummary,
  type LearningPathGraph,
  type LearningResource,
  type LearningFeedback,
  type AgentRequest,
  type WorkflowResult,
  type SaveResourceResponse,
  type TaskOutput,
  type TaskBranch,
  type OutputComment,
  type GenerationResult,
  type Project,
  type ProjectMember,
  type ProjectTask,
  type CreateProjectBody,
  type Artifact,
  type ArtifactDetail,
  type PromptTemplate,
  type PromptVersion,
  type PromptTaskType,
  type CreateTemplateBody,
  type UpdateTemplateBody,
  type CreateVersionBody,
  type ReviewRequest,
  type ReviewDetail,
  type IssueTag,
  type CompleteReviewBody,
  type Invocation,
  type InvocationDetail,
  type ModelProvider,
  type AIModel,
  type TaskType,
  type ApiConfig,
  type OperationLog,
  type LoginLog,
  type StatisticsOverview,
  type ProjectStats,
  type ModelCallStats,
  type CostStats,
  type ReviewStats,
  type MemberContribution,
  type RecentActivity,
  type LearningOverview,
  type MasteryDist,
  type WeakKnowledgePoint,
  type ResourceTypeDist,
  type InvocationTrend,
  type ReviewRateByCourse,
  type CostDistribution,
} from './api/index'

export { client as default } from './api/index'
